### ISSUE TITLE
Importing resources.protobuf.* results in errors

### ISSUE THREAD

**Issue by slothsec** [matchaxnb/pyiwa#1]
Hey,

I have the following error when trying to run pyiwa.py on a Mac (10.14.40) with python2 (2.7.16).

```
python2 pyiwa.py 
Traceback (most recent call last):
  File "pyiwa.py", line 38, in <module>
    import resources.protobuf.TSWPCommandArchives_pb2
  File "/Users/me/Desktop/Index/pyiwa/resources/protobuf/TSWPCommandArchives_pb2.py", line 16, in <module>
    import TSWPArchives_pb2
  File "/Users/me/Desktop/Index/pyiwa/resources/protobuf/TSWPArchives_pb2.py", line 21, in <module>
    nge\x18\x03 \x01(\x0b\x32\n.TSP.Range\"M\n\x10RubyFieldArchive\x12&\n\x05super\x18\x01 \x01(\x0b\x32\x17.TSWP.SmartFieldArchive\x12\x11\n\truby_text\x18\x02 \x01(\t\"\xc8\x01\n\rChangeArchive\x12,\n\x04kind\x18\x01 \x01(\x0e\x32\x1e.TSWP.ChangeArchive.ChangeKind\x12\x1f\n\x07session\x18\x02 \x01(\x0b\x32\x0e.TSP.Reference\x12\x17\n\x04\x64\x61te\x18\x03 \x01(\x0b\x32\t.TSP.Date\x12\x0e\n\x06hidden\x18\x04 \x01(\x08\"?\n\nChangeKind\x12\x18\n\x14kChangeKindInsertion\x10\x01\x12\x17\n\x13kChangeKindDeletion\x10\x02\"d\n\x14\x43hangeSessionArchive\x12\x13\n\x0bsession_uid\x18\x01 \x01(\r\x12\x1e\n\x06\x61uthor\x18\x02 \x01(\x0b\x32\x0e.TSP.Reference\x12\x17\n\x04\x64\x61te\x18\x03 \x01(\x0b\x32\t.TSP.Date\"\x1b\n\x19SectionPlaceholderArchive*\xf4\x01\n\rSelectionType\x12\x18\n\x14SelectionType_Normal\x10\x00\x12\x1b\n\x17SelectionType_ListLabel\x10\x01\x12\x1b\n\x17SelectionType_ListTopic\x10\x02\x12\x19\n\x15SelectionType_Replace\x10\x03\x12 \n\x1cSelectionType_CopyPasteStyle\x10\x04\x12\x1a\n\x16SelectionType_Replace2\x10\x05\x12\x1c\n\x18SelectionType_SmartField\x10\x06\x12\x18\n\x14SelectionType_Visual\x10\x07*\x86\x01\n\x16StyleInsertionBehavior\x12!\n\x1dStyleInsertionBehavior_NoGrow\x10\x00\x12#\n\x1fStyleInsertionBehavior_GrowLeft\x10\x01\x12$\n StyleInsertionBehavior_GrowRight\x10\x02*?\n\rCaretAffinity\x12\x17\n\x13\x43\x61retAffinity_Start\x10\x00\x12\x15\n\x11\x43\x61retAffinity_End\x10\x01*\x81\x01\n\x14WritingDirectionType\x12%\n\x18kWritingDirectionNatural\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12 \n\x1ckWritingDirectionLeftToRight\x10\x00\x12 \n\x1ckWritingDirectionRightToLeft\x10\x01')
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 884, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "TSWPArchives.proto":
  TSWP.ThemePresetsArchive.extension: The extension TSWP.ThemePresetsArchive.extension cannot be required.
```

Similar error seem to occur with all the `import resources.protobuf.*` statements. I had a quick look at what would be involved to resolve but I got pretty lost. I figure I need to update the `serialized_pb` value, though I am unsure how this value is being created. 

Any points in the right direction would be appreciated.

Thanks

**Comment by matchaxnb** [comment]
Hey,

All this was done on iWork '13 to dump text from damaged files.

Maybe you need to update the schemas before anything.

https://github.com/sajari/docconv/tree/master/iWork/pb-schema I used that back then.

Feel free to fork and add support for newer formats.

<3
Mat
